---
# Copyright (C) 2015-2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2015-2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Configure APT Cacher NG with AppArmor
  import_playbook: apt_cacher_ng.yml

- name: Configure Bitcoin Daemon
  import_playbook: bitcoind.yml

- name: Configure brtfs filesystem
  import_playbook: btrfs.yml

- name: Configure DNSmasq with AppArmor
  import_playbook: dnsmasq.yml

- name: Configure Firejail service
  import_playbook: firejail.yml

- name: Configure Foodsoft application
  import_playbook: foodsoft.yml

- name: Configure FUSE service
  import_playbook: fuse.yml

- name: Configure HomeAssistant
  import_playbook: homeassistant.yml

- name: Configure Kodi application
  import_playbook: kodi.yml

- name: Configure snapshot-snapper for btrfs
  import_playbook: snapshot_snapper.yml

- name: Configure Tor Relay
  import_playbook: tor.yml

- name: Configure Volkszaehler application
  import_playbook: volkszaehler.yml

- name: Configure X2Go Server
  import_playbook: x2go_server.yml
||||||| parent of a026e3ca4 ([dnsmasq] Make use of the new debops.apparmor role)
- import_playbook: apt_cacher_ng.yml
- import_playbook: bitcoind.yml
- import_playbook: btrfs.yml
- import_playbook: dnsmasq.yml
- import_playbook: firejail.yml
- import_playbook: foodsoft.yml
- import_playbook: fuse.yml
- import_playbook: homeassistant.yml
- import_playbook: kodi.yml
- import_playbook: snapshot_snapper.yml
- import_playbook: tor.yml
- import_playbook: volkszaehler.yml
- import_playbook: x2go_server.yml
